//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMiniPrj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public Nullable<int> TrainNumber { get; set; }
        public string TicketClass { get; set; }
        public string SeatPreference { get; set; }
        public string PassengerName { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> DateOfTravel { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> NumberOfTickets { get; set; }
        public Nullable<decimal> TicketPrice { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
